# conda env create --file environment.yml

name: antarticIST
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - invoke
  - jupyter
  - jupyterlab
  - matplotlib
  - netCDF4
  - numpy
  - pandas
  - pip
  - plotly
  - python=3.8